### ISSUE TITLE
When adding BCC destination the TO field is empty

### ISSUE THREAD

**Issue by codenameone** [sendgrid/sendgrid-google-java#11]
I'm not exactly sure if I'm doing this right but the idea is to provide automation for a "personal" email. So I'm bcc'ing myself on outgoing emails to know that I sent a welcome email to person X. 
However, the email that I'm receiving has no indication to whom it was sent.

Is there a way to add a "proper" bcc in sendgrid?

**Comment by danielamihalache** [comment]
addBcc() was removed because is currently not supported.Standard setBcc will hide who the email is addressed to. This is by design. Additionally, it is a good idea to use multiple addTos instead addBcc(this is currently not supported) and each user will receive a personalized email showing only their email.

**Comment by codenameone** [comment]
Thanks. Its a shame since neither this or the suggested solution solve my use case.

**Comment by danielamihalache** [comment]
The only workaround will be to set use_headers variable to false:
Sendgrid mail = new Sendgrid("<user>","<password>");
mail.use_headers = false;
mail.setBcc("foo@example.com");

But this way you will show all the recipients(because headers are not set and also you will not be able to use categories, filters, substitutions, etc.)
